#make a christmas tree
print("             *              ")
print("            ***             ")
print("           *****            ")
print("         *********          ")
print("       *************        ")
print("      ***************       ")
print("    *******************     ")
print("   **********************  ")
print("             ||             ")
print("             ||             ")
print("             ||             ")
print("             ||             ")